<?php
define('kInGameID', 0);
define('kLastName', 1);
define('kFirstName', 2);
//define ('kPosition', 1);
define('PosGrp', 3);
define('School', 4);
//define (kTeam, 4);
//define (kBorn, 5);
//define (kHomeTown, 6);
//define (kAgent, 7);
//define (kDesignation, 8);
define('Height', 5);
define('Weight', 6);
//define (kExperience, 11);
//define (kVolatility, 12);
//define (kJersey, 13);
//define (kLoyalty, 14);
//define (kWinner, 15);
//define (kLeader, 16);
//define (kIntelligence, 17);
//define (kPersonality, 18);
//define (kPopularity, 19);
//define (kMentorTo, 20);
define('Solecismic', 8);
define('Forty', 7);
define('BenchPress', 9);
define('Agility', 10);
define('BroadJump', 11);
define('PositionDrill', 12);
define('Developed', 13);
define('Grade', 14);
//define (kInterviewed, 28);
//define (kImpression, 29);
//define (kCurrent, 30);
//define (kFuture, 31);
//define (kConflicts, 32);
//define (kAffinities, 33);
//define (kCharacter, 34);
define('InterrogatorPlayerID', 0);
define('InterrogatorLastName', 1);
define('InterrogatorFirstName', 2);

define('staff_id', 0);
define('staff_first_name', 2);
define('staff_last_name', 1);
define('staff_curr_team_id', 3);
define('staff_role', 4);
define('staff_pri_group', 5);
define('staff_salary', 6);
define('staff_player_dev', 7);
define('staff_young_player_dev', 8);
define('staff_motivation', 9);
define('staff_discipline', 10);
define('staff_play_calling', 11);
define('staff_str_training', 12);
define('staff_conditioning', 13);
define('staff_intelligence', 14);
define('staff_scouting', 15);
define('staff_interviewing', 16);
define('staff_age', 17);
define('staff_retired', 18);
define('staff_yrs_on_contract', 19);
define('staff_suitable_hc', 20);
define('staff_suitable_oc', 21);
define('staff_suitable_dc', 22);
define('staff_suitable_ac', 23);
define('staff_suitable_sc', 24);

define('trans_stage', 0);
define('trans_year', 1);
define('trans_player_id', 2);
define('trans_trans', 3);
define('trans_team_id', 4);
define('trans_position', 5);

define('pr_player_id', 0);
define('prating_player_id', 2);
define('pr_team', 5);
define('pr_position', 2);
define('prating_current', 62);
define('prating_future', 63);

define('RatingPlayer_ID', 2);
define('RatingScouting', 3);
define('RatingScreen_Passes', 4);
define('RatingShort_Passes', 5);
define('RatingMedium_Passes', 6);
define('RatingLong_Passes', 7);
define('RatingDeep_Passes', 8);
define('RatingThird_Down', 9);
define('RatingRun_Frequency', 10);
define('RatingFuture_1', 11);
define('RatingAccuracy', 12);
define('RatingTiming', 13);
define('RatingSense_Rush', 14);
define('RatingRead_Defense', 15);
define('RatingTwo_Minute_Offense', 16);
define('RatingFuture_2', 17);
define('RatingFuture_3', 18);
define('RatingFuture_4', 19);
define('RatingFuture_5', 20);
define('RatingFuture_6', 21);
define('RatingSpeed', 22);
define('RatingPower_Inside', 23);
define('RatingThird_Down_Runs', 24);
define('RatingHole_Recognition', 25);
define('RatingElusiveness', 26);
define('RatingSpeed_Outside', 27);
define('RatingBlitz_Pickup', 28);
define('RatingAvoid_Drops', 29);
define('RatingGet_Downfield', 30);
define('RatingRoute_Running', 31);
define('RatingThird_Down_Receiving', 32);
define('RatingBig_Play_Receiving', 33);
define('RatingCourage', 34);
define('RatingAdjust_to_Ball', 35);
define('RatingPunt_Returns', 36);
define('RatingKick_Returns', 37);
define('RatingFuture_7', 38);
define('RatingRun_Blocking', 39);
define('RatingPass_Blocking', 40);
define('RatingBlocking_Strength', 41);
define('RatingPunting_Power', 42);
define('RatingHang_Time', 43);
define('RatingDirectional_Punting', 44);
define('RatingKickoff_Distance', 45);
define('RatingKickoff_Hang_Time', 46);
define('RatingKicking_Accuracy', 47);
define('RatingKicking_Power', 48);
define('RatingRun_Defense', 49);
define('RatingPass_Rush_Technique', 50);
define('RatingMan_to_Man_Defense', 51);
define('RatingZone_Defense', 52);
define('RatingBumpandRun_Defense', 53);
define('RatingPass_Rush_Strength', 54);
define('RatingPlay_Diagnosis', 55);
define('RatingPunishing_Hitter', 56);
define('RatingIntercepting', 57);
define('RatingEndurance', 58);
define('RatingSpecial_Teams', 59);
define('RatingLong_Snapping', 60);
define('RatingKick_Holding', 61);
define('RatingCurrent_Overall', 62);
define('RatingFuture_Overall', 63);

define('InfoPlayer_ID', 0);
define('InfoLast_Name', 1);
define('InfoFirst_Name', 2);
define('InfoJunior_Flag', 3);
define('InfoNickname', 4);
define('InfoPosition', 5);
define('InfoHeight', 10);
define('InfoWeight', 11);
define('InfoYear_Born', 16);
define('InfoMonth_Born', 17);
define('InfoDay_Born', 18);
define('InfoCollege', 19);
define('InfoExperience', 32);

define('RecordPlayer_ID', 0);
define('RecordUniform_Number', 1);
define('RecordPosition', 2);
define('RecordExperience', 3);
define('RecordLoyalty', 9);
define('RecordPlay_for_Winner', 10);
define('RecordPersonality_Strength', 11);
define('RecordLeadership', 12);
define('RecordIntelligence', 13);
define('RecordVolatility', 16);
define('RecordPopularity', 20);
        
$valid_fof7_rookie = 'Player_ID,Last_Name,First_Name,Position_Group,College,Height,Weight,Dash,Solecismic,Strength,Agility,Jump,Position_Specific,Developed,Grade';
$valid_fof7_staff = 'Staff_ID,Last_Name,First_Name,Current_Team,Role,Primary_Group,Salary,Player_Development,Young_Player_Development,Motivation,Discipline,Play_Calling,Strength_Training,Conditioning,Intelligence,Scouting_Ability,Interviewing,Age,Retired,Years_on_Contract,Suitable_Head_Coach,Suitable_Offensive_Coordinator,Suitable_Defensive_Coordinator,Suitable_Assistant_Coach,Suitable_Strength_Coordinator';
$valid_fof7_transaction = 'Stage,Year,Player_ID/Staff_ID/Round,Transaction,Team,Position_Group/Year,Money,Years/Original_Position/Destination_City,Original_Team/Destination_Position/Misc.';
$valid_fof7_player_record = 'Player_ID,Uniform_Number,Position,Experience,Position_Group,Team,Injury_Length,Health,Injury_Type,Loyalty,Play_for_Winner,Personality_Strength,Leadership,Intelligence,Red_Flag,Mentor,Volatility,Designation,Status,Year_Signed,Popularity,How_Acquired,Hall_Of_Fame_Points,Contract_Length,Salary_Year_1,Salary_Year_2,Salary_Year_3,Salary_Year_4,Salary_Year_5,Bonus_Year_1,Bonus_Year_2,Bonus_Year_3,Bonus_Year_4,Bonus_Year_5,Holdout,Special_Teams_Designation,Season_Statistics_-_S_Games_Played,S_Games_Started,S_Pass_Attempts,S_Pass_Completions,S_Passing_Yards,S_Long_Pass,S_Touchdown_Passes,S_Intercepted,S_Sacked,S_Sack_Yards,S_Rushes,S_Rushing_Yards,S_Long_Rush,S_Rushing_Touchdowns,S_Catches,S_Receiving_Yards,S_Long_Reception,S_Receiving_Touchdowns,S_Targets,S_Yards_after_Catch,S_Drops,S_Punt_Returns,S_Punt_Return_Yards,S_Punt_Returns_Touchdowns,S_Kick_Returns,S_Kick_Return_Yards,S_Kick_Return_Touchdowns,S_Fumbles,S_Fumbles_Recovered,S_Fumbles_Forced,S_Fumble_Return_Touchdowns,S_Key_Run_Blocks,S_Block_Opportunities,S_Sacks_Allowed,S_Tackles,S_Assists,S_Sacks_(x10),S_Interceptions,S_Interception_Return_Yards,S_Interception_Return_Touchdowns,S_Passes_Defensed,S_Passes_Blocked,S_Hurries,S_Caught_Against,S_Pass_Plays,S_Run_Plays,S_Field_Goals_Made,S_Field_Goals_Attempted,S_Long_Field_Goal,S_Points_After_Touchdown,S_PATs_Attempted,S_Punts,S_Punting_Yards,S_Long_Punt,S_Punts_Inside_20,S_Points_Scored,S_HoF_Points,S_Third_Down_-_Runs,S_3D_First_Downs_-_Runs,S_3D_Pass_Attempts,S_3D_Completions,S_3D_First_Downs_-_Passes,S_3D_Targets,S_3D_Catches,S_3D_First_Downs_-_Catches,S_First_Down_-_Runs,S_First_Down_Pass_Attempts,S_First_Down_Catches,S_40+_Field_Goals_Attempted,S_40+_Field_Goals_Made,S_50+_Field_Goals_Attempted,S_50+_Field_Goals_Made,S_Net_Punting_Yardage,S_Special_Teams_Tackles,S_Quarterback_Knocked_Down,S_Red_Zone_-_Runs,S_RZ_Rushing_Yards,S_RZ_Pass_Attempts,S_RZ_Completions,S_RZ_Passing_Yards,S_RZ_Targets,S_RZ_Catches,S_RZ_Receiving_Yards,S_Total_Touchdowns,S_Two-Point_Conversions,S_Pancake_Blocks,S_Quarterback_Knockdowns,S_Special_Teams_Plays,S_100-Yard_Rushing_Games,S_100-Yard_Receiving_Games,S_300-Yard_Passing_Games,S_10-Yard_Runs,S_20-Yard_Catches,S_20-Yard_Completions,S_Yards_from_Scrimmage,S_All-Purpose_Yards,Playoff_Statistics_-_P_Games_Played,P_Games_Started,P_Pass_Attempts,P_Pass_Completions,P_Passing_Yards,P_Long_Pass,P_Touchdown_Passes,P_Intercepted,P_Sacked,P_Sack_Yards,P_Rushes,P_Rushing_Yards,P_Long_Rush,P_Rushing_Touchdowns,P_Catches,P_Receiving_Yards,P_Long_Reception,P_Receiving_Touchdowns,P_Targets,P_Yards_after_Catch,P_Drops,P_Punt_Returns,P_Punt_Return_Yards,P_Punt_Returns_Touchdowns,P_Kick_Returns,P_Kick_Return_Yards,P_Kick_Return_Touchdowns,P_Fumbles,P_Fumbles_Recovered,P_FumbleP_Forced,P_Fumble_Return_Touchdowns,P_Key_Run_Blocks,P_Block_Opportunities,P_Sacks_Allowed,P_Tackles,P_Assists,P_Sacks_(x10),P_Interceptions,P_Interception_Return_Yards,P_Interception_Return_Touchdowns,P_Passes_Defensed,P_Passes_Blocked,P_Hurries,P_Caught_Against,P_Pass_Plays,P_Run_Plays,P_Field_Goals_Made,P_Field_Goals_Attempted,P_Long_Field_Goal,P_Points_After_Touchdown,P_PATs_Attempted,P_Punts,P_Punting_Yards,P_Long_Punt,P_Punts_Inside_20,P_Points_Scored,P_HoF_Points,P_Third_Down_-_Runs,P_3D_First_Downs_-_Runs,P_3D_Pass_Attempts,P_3D_Completions,P_3D_First_Downs_-_Passes,P_3D_Targets,P_3D_Catches,P_3D_First_Downs_-_Catches,P_First_Down_-_Runs,P_First_Down_Pass_Attempts,P_First_Down_Catches,P_40+_Field_Goals_Attempted,P_40+_Field_Goals_Made,P_50+_Field_Goals_Attempted,P_50+_Field_Goals_Made,P_Net_Punting_Yardage,P_Special_Teams_Tackles,P_Quarterback_Knocked_Down,P_Red_Zone_-_Runs,P_RZ_Rushing_Yards,P_RZ_Pass_Attempts,P_RZ_Completions,P_RZ_Passing_Yards,P_RZ_Targets,P_RZ_Catches,P_RZ_Receiving_Yards,P_Total_Touchdowns,P_Two-Point_Conversions,P_Pancake_Blocks,P_Quarterback_Knockdowns,P_Special_Teams_Plays,P_100-Yard_Rushing_Games,P_100-Yard_Receiving_Games,P_300-Yard_Passing_Games,P_10-Yard_Runs,P_20-Yard_Catches,P_20-Yard_Completions,P_Yards_from_Scrimmage,P_All-Purpose_Yards,Pointer_to_Active_Free_Agent_Block,Pointer_to_Player_Information_Record';
$valid_fof7_player_ratings = 'Record_Number,Year,Player_ID,Scouting,Screen_Passes,Short_Passes,Medium_Passes,Long_Passes,Deep_Passes,Third_Down,Run_Frequency,Future_1,Accuracy,Timing,Sense_Rush,Read_Defense,Two-Minute_Offense,Future_2,Future_3,Future_4,Future_5,Future_6,Speed,Power_Inside,Third-Down_Runs,Hole_Recognition,Elusiveness,Speed_Outside,Blitz_Pickup,Avoid_Drops,Get_Downfield,Route_Running,Third-Down_Receiving,Big_Play_Receiving,Courage,Adjust_to_Ball,Punt_Returns,Kick_Returns,Future_7,Run_Blocking,Pass_Blocking,Blocking_Strength,Punting_Power,Hang_Time,Directional_Punting,Kickoff_Distance,Kickoff_Hang_Time,Kicking_Accuracy,Kicking_Power,Run_Defense,Pass_Rush_Technique,Man-to-Man_Defense,Zone_Defense,Bump-and-Run_Defense,Pass_Rush_Strength,Play_Diagnosis,Punishing_Hitter,Intercepting,Endurance,Special_Teams,Long_Snapping,Kick_Holding,Current_Overall,Future_Overall';
$valid_fof7_player_info = 'Player_ID,Last_Name,First_Name,Junior_Flag,Nickname,Position,Player_of_Game_Count,Championship_Rings,Player_of_the_Week_Count,Player_of_the_Week_Win,Height,Weight,Hall_of_Fame_Flag,Year_Inducted,Percentage_of_Vote,Chosen_Team,Year_Born,Month_Born,Day_Born,College,Draft_Round,Drafted_Position,Drafted_By,Draft_Year,4th_Quarter_Comebacks,Quarterback_Wins,Quarterback_Losses,Quarterback_Ties,Home_Town,Home_State,Career_Games_Played,Number_of_Seasons,Season_1_Pointer_to_Player_Year_Data,SP_2,SP_3,SP_4,SP_5,SP_6,SP_7,SP_8,SP_9,SP_10,SP_11,SP_12,SP_13,SP_14,SP_15,SP_16,SP_17,SP_18,SP_19,SP_20,Season_1_Year,SY_2,SY_3,SY_4,SY_5,SY_6,SY_7,SY_8,SY_9,SY_10,SY_11,SY_12,SY_13,SY_14,SY_15,SY_16,SY_17,SY_18,SY_19,SY_20';
$valid_fof7_active_qb = 'Player_ID,Number_Formations,I_Normal,I_TE_Pairs,I_WR_Slot,Pro_Normal,Pro_TE_Pairs,Pro_WR_Slot,Weak_Normal,Weak_TE_Pairs,Weak_Three_WR,Strong_Normal,Strong_TE_Pairs,Strong_Three_WR,Single-Back_Normal,Single-Back_TE_Pairs,Single-Back_Trips_WR,Single-Back_Four_WR,Five_WR_Spread,Goal_Line_Three_TE';
//$valid_extractor = 'Name,Position,PosGrp,College,Team,Born,HomeTown,Agent,Designation,Height,Weight,Experience,Volatility,Jersey,Loyalty,Winner,Leader,Intelligence,Personality,Popularity,MentorTo,Solecismic,40Yard,Bench,Agility,BroadJump,PosDrill,PctDev,Intvwd,Impress,Cur,Fut,Conflicts,Affinities,Character';
$valid_fof7_rookie_ratings = 'Player_ID,Interviewed,Low_Screen_Passes,Low_Short_Passes,Low_Medium_Passes,Low_Long_Passes,Low_Deep_Passes,Low_Third_Down,Low_Run_Frequency,Low_Future_1,Low_Accuracy,Low_Timing,Low_Sense_Rush,Low_Read_Defense,Low_Two-Minute_Offense,Low_Future_2,Low_Future_3,Low_Future_4,Low_Future_5,Low_Future_6,Low_Speed,Low_Power_Inside,Low_Third-Down_Runs,Low_Hole_Recognition,Low_Elusiveness,Low_Speed_Outside,Low_Blitz_Pickup,Low_Avoid_Drops,Low_Get_Downfield,Low_Route_Running,Low_Third-Down_Receiving,Low_Big_Play_Receiving,Low_Courage,Low_Adjust_to_Ball,Low_Punt_Returns,Low_Kick_Returns,Low_Future_7,Low_Run_Blocking,Low_Pass_Blocking,Low_Blocking_Strength,Low_Punting_Power,Low_Hang_Time,Low_Directional_Punting,Low_Kickoff_Distance,Low_Kickoff_Hang_Time,Low_Kicking_Accuracy,Low_Kicking_Power,Low_Run_Defense,Low_Pass_Rush_Technique,Low_Man-to-Man_Defense,Low_Zone_Defense,Low_Bump-and-Run_Defense,Low_Pass_Rush_Strength,Low_Play_Diagnosis,Low_Punishing_Hitter,Low_Intercepting,Low_Endurance,Low_Special_Teams,Low_Long_Snapping,Low_Kick_Holding,High_Screen_Passes,High_Short_Passes,High_Medium_Passes,High_Long_Passes,High_Deep_Passes,High_Third_Down,High_Run_Frequency,High_Future_1,High_Accuracy,High_Timing,High_Sense_Rush,High_Read_Defense,High_Two-Minute_Offense,High_Future_2,High_Future_3,High_Future_4,High_Future_5,High_Future_6,High_Speed,High_Power_Inside,High_Third-Down_Runs,High_Hole_Recognition,High_Elusiveness,High_Speed_Outside,High_Blitz_Pickup,High_Avoid_Drops,High_Get_Downfield,High_Route_Running,High_Third-Down_Receiving,High_Big_Play_Receiving,High_Courage,High_Adjust_to_Ball,High_Punt_Returns,High_Kick_Returns,High_Future_7,High_Run_Blocking,High_Pass_Blocking,High_Blocking_Strength,High_Punting_Power,High_Hang_Time,High_Directional_Punting,High_Kickoff_Distance,High_Kickoff_Hang_Time,High_Kicking_Accuracy,High_Kicking_Power,High_Run_Defense,High_Pass_Rush_Technique,High_Man-to-Man_Defense,High_Zone_Defense,High_Bump-and-Run_Defense,High_Pass_Rush_Strength,High_Play_Diagnosis,High_Punishing_Hitter,High_Intercepting,High_Endurance,High_Special_Teams,High_Long_Snapping,High_Kick_Holding';
$valid_fof7_player_personal_ratings = 'Player_ID,Current_Screen_Passes,Current_Short_Passes,Current_Medium_Passes,Current_Long_Passes,Current_Deep_Passes,Current_Third_Down,Current_Run_Frequency,Current_Future_1,Current_Accuracy,Current_Timing,Current_Sense_Rush,Current_Read_Defense,Current_Two-Minute_Offense,Current_Future_2,Current_Future_3,Current_Future_4,Current_Future_5,Current_Future_6,Current_Speed,Current_Power_Inside,Current_Third-Down_Runs,Current_Hole_Recognition,Current_Elusiveness,Current_Speed_Outside,Current_Blitz_Pickup,Current_Avoid_Drops,Current_Get_Downfield,Current_Route_Running,Current_Third-Down_Receiving,Current_Big_Play_Receiving,Current_Courage,Current_Adjust_to_Ball,Current_Punt_Returns,Current_Kick_Returns,Current_Future_7,Current_Run_Blocking,Current_Pass_Blocking,Current_Blocking_Strength,Current_Punting_Power,Current_Hang_Time,Current_Directional_Punting,Current_Kickoff_Distance,Current_Kickoff_Hang_Time,Current_Kicking_Accuracy,Current_Kicking_Power,Current_Run_Defense,Current_Pass_Rush_Technique,Current_Man-to-Man_Defense,Current_Zone_Defense,Current_Bump-and-Run_Defense,Current_Pass_Rush_Strength,Current_Play_Diagnosis,Current_Punishing_Hitter,Current_Intercepting,Current_Endurance,Current_Special_Teams,Current_Long_Snapping,Current_Kick_Holding,Current_Overall,Future_Screen_Passes,Future_Short_Passes,Future_Medium_Passes,Future_Long_Passes,Future_Deep_Passes,Future_Third_Down,Future_Run_Frequency,Future_Future_1,Future_Accuracy,Future_Timing,Future_Sense_Rush,Future_Read_Defense,Future_Two-Minute_Offense,Future_Future_2,Future_Future_3,Future_Future_4,Future_Future_5,Future_Future_6,Future_Speed,Future_Power_Inside,Future_Third-Down_Runs,Future_Hole_Recognition,Future_Elusiveness,Future_Speed_Outside,Future_Blitz_Pickup,Future_Avoid_Drops,Future_Get_Downfield,Future_Route_Running,Future_Third-Down_Receiving,Future_Big_Play_Receiving,Future_Courage,Future_Adjust_to_Ball,Future_Punt_Returns,Future_Kick_Returns,Future_Future_7,Future_Run_Blocking,Future_Pass_Blocking,Future_Blocking_Strength,Future_Punting_Power,Future_Hang_Time,Future_Directional_Punting,Future_Kickoff_Distance,Future_Kickoff_Hang_Time,Future_Kicking_Accuracy,Future_Kicking_Power,Future_Run_Defense,Future_Pass_Rush_Technique,Future_Man-to-Man_Defense,Future_Zone_Defense,Future_Bump-and-Run_Defense,Future_Pass_Rush_Strength,Future_Play_Diagnosis,Future_Punishing_Hitter,Future_Intercepting,Future_Endurance,Future_Special_Teams,Future_Long_Snapping,Future_Kick_Holding,Future_Overall';

// Preload the position mapping
$positions = [];
$statement = "select * from position_to_alias";
$result = mysqli_query($mysql, $statement);
while ($row = mysqli_fetch_array($result)) {
    $positions[$row['alias_name']] = $row['position_id'];
}
